### ISSUE TITLE
How to open "about:home". (Firefox for Android)

### ISSUE THREAD

**Issue by utubo** [utubo/firefox-simple_gesture#21]
https://bugzilla.mozilla.org/show_bug.cgi?id=1400555

 - [x] `location.href ='about:home'` 😢 This does not work.
 - [x] `tabs.create({url:'about:home'})` 😢 This does not work.
 - [x] `tabs.create({url:'about:home#'})` 😢 This does not work.
 - [x] `tabs.create({url:'about:home?'})` 😢 This does not work.
 - [x] `tabs.create({})` 😢 "about:blank" is opened.
 - [x] Redirect with `webRequest.onBeforeRequest` 😢 "about:blank" is opened.
 - [x] Redirect with `webNavigation.onBefore` 😢 This can't redirect.
 - [x] Close all tabs and reopen all tab's urls 😢 This works. But, all sessions are removed.
 - [x] Close all tabs and restore all sessions 😢 Firefox for Android does not support sessions API.
 - [x] Focus to address-bar 😢 Webextension can't this.
 - [x] Focus to address-bar with simulating key events 😢 This does not work.
 - [x] Show `<a href="about:home">click me</a>` 😢 This link does not work.
 - [x] History back to "about:home" 😢 This does not work when open from shortcut.
 - [x] `window.BrowserApp.addTab('about:home')` on background.js 😢 BrowserApp is undefined.
 - [x] `window.BrowserApp.addTab('about:home')` on content.js 😢 BrowserApp is undefined.
 - [x] `tabs.duplicate(/*"about:home"'s tabId*/)` 😢 This does not work.
 - [x] Add permission "ActiveTab", and redirect "about:blank" to "about:home" 😢 This does not work.
 - [x] `location.replace('about:home')` 😢 This does not work.
 - [x] `location.assgin('about:home')` 😢 This does not work.
 - [x] `tabs.update(tabId, { url: 'about:home' })` 😢 This does not work.
 - [x] Click tab button with Webextensions 😢 Webextension can't this.

**Comment by utubo** [comment]
ここにヒントがないかなぁ
https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/browser.js

**Comment by Efreak** [comment]
`about:home` no longer exists on mobile

**Comment by utubo** [comment]
😢😢😢😢😢
