### ISSUE TITLE
Custom gesturesを保存したときの画面遷移がおかしい

### ISSUE THREAD

**Issue by h-youhei** [utubo/firefox-simple_gesture#37]
simple_gesture 2.4
android 4.4.2
firefox 58.0.1

Scriptを編集して保存すると、New tab のところに飛びます。
Custom gestures のところに飛んでほしいです。

Scriptを編集せずに保存するとスクロールは起こりません。

**Comment by h-youhei** [comment]
画面遷移がおかしいのはScriptにエラーがあるときだけでした。

**Comment by utubo** [comment]
報告ありがとうございます現象確認しました。
どうもソフトウェアキーボードが表示されたタイミングで裏でスクロールしてるんじゃないかという雰囲気です。（別のアドオンで経験あり）。
近日中にちょっと強引に対処してみます。

**Comment by utubo** [comment]
修正してみました。(ver. 2.4.1)
ページの高さの指定に`min-height: 100vh`を指定していたのが問題だったみたいなので、
画面表示時に固定pxを設定するようにしました。
画面を回転させても反映されないけれどそれは諦め。

**Comment by h-youhei** [comment]
修正確認しました。ありがとうございます、

**Comment by utubo** [comment]
よかった
ありがとうございました。助かりました。

**Comment by utubo** [comment]
原因まとめ
https://twitter.com/utbutb/statuses/959043720367624192
