### ISSUE TITLE
Firefox Quantum for Windows Support

### ISSUE THREAD

**Issue by balthanon** [utubo/firefox-simple_gesture#48]
Any chance of getting a version of this for Firefox Quantum on Windows?  I would love to use Firefox as my primary browser on my tablet, but the lack of gesture support is a too painful.

**Comment by balthanon** [comment]
Thanks, I'll be happy to give it a shot and report back.

**Comment by utubo** [comment]
😊
I close this issue.

**Comment by utubo** [comment]
まちがった…報告くれるのか！
Sorry, I had mistaken the meaning.
If there are any problems , Please reopen this issue.
