### ISSUE TITLE
Add more memorable gestures

### ISSUE THREAD

**Issue by fluks** [utubo/firefox-simple_gesture#50]
I find current gestures difficult to remember, because I don't use gestures a lot. Arrows would be easier to remember for back and forward, for instance. Reload could be a circle etc.

Perhaps there are libraries that could be used to recognize more complex gestures. [Here's one](https://depts.washington.edu/madlab/proj/dollar/index.html). The demo doesn't work on touchscreen, though, but maybe it can be fixed.

What do you think?

**Comment by utubo** [comment]
(I use google translation application.)

Complex processing may consume a lot of smartphone's battery.
Also, I tried it before but it was difficult if the diagonal input was a small device.
However, at that time, I did not know this library, so it may change the result again as I tried it.
I am busy with work now, but I think I will give it a try if there is a chance.
Thank you for introducing the library.
(Of course, it is greatly appreciated that you create add-ons with that library!)


Just to be sure, I write the same thing in my mother tongue.
複雑な処理はスマートフォンのバッテリーを大きく消費してしまうかもしれません。
また、以前に試したのですが斜めの入力は小さいデバイスだと難しかったです。
ですが、そのときは、そのライブラリを知らなかったので試してみたらまた結果が変わるかもしれません。
今は仕事が忙しいのですが機会があったら試してみようと思います。
ライブラリを紹介してくださってありがとうございました。
（もちろん、あなたがこのライブラリを使ってアドオンを作成するのは大歓迎です！）

**Comment by fluks** [comment]
Ok, I will try to play with this library too, if I have time. Thanks.

**Comment by utubo** [comment]
Maybe, I will create a new add-on  if I have time...
So, I close this Issue and create a new Project.
  https://github.com/utubo/firefox-touch_gesture/projects/1

時間があったら新しいアドオンを作るかもしれません。
よって、別のプロジェクトで管理します。このIssueはCloseします。
