### ISSUE TITLE
Hard to use on zoomed page

### ISSUE THREAD

**Issue by byzod** [utubo/firefox-simple_gesture#55]
The gesture size detection is relative to the page size, but not the screen space.

Thus if you zoom in the page, you need to draw bigger gesture to trigger it. If zoom in too near, it's impossible to trigger any gesture.

**Comment by utubo** [comment]
When zoom in the page, Firefox for Android returns wrong touch positoin and scroll position. (since FF 65?)
Perhaps I will not be able to fix this.
Plz wait firefox is fixed.
Thx for your review.

**Comment by utubo** [comment]
test
https://utb.sakura.ne.jp/samples/positions_test.html

**Comment by utubo** [comment]
maybe
```
Screen
  View (for zoom and smooth scroll ) ?   I can't get this scroll position.
    Window object
      documentElements
```

**Comment by utubo** [comment]
有力な情報
https://drafts.csswg.org/cssom-view/#dom-window-scrollx

**Comment by utubo** [comment]
I can get visualViewport position !
https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport

try update Simple-Gesture to 2.14.1, open `about:config` and set `dom.visualviewport.enabled` to `true`.

**Comment by utubo** [comment]
- [ ] The toast too wide on zoomed page
- [ ] "When page is zoomed" -> "On zoomed page"
