### ISSUE TITLE
Add-on Not Supported when trying to add new newest Firefox

### ISSUE THREAD

**Issue by fbegue** [utubo/firefox-simple_gesture#68]
First time trying to use this addon, but when I visit the [add-on listing](https://addons.mozilla.org/en-US/android/addon/simple-gesture/) on Android, I can't install it.

- the "Add to Firefox" button is greyed out
- clicking the "Download file" link reports "Add-on Not Supported"

Android 10
Firefox 107

**Comment by utubo** [comment]
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

Set your collection or https://addons.mozilla.org/firefox/collections/16201230/What-I-want-on-Fenix/

**Comment by utubo** [comment]
I added `Installation` to `About this extension` of https://addons.mozilla.org/en-US/firefox/addon/simple-gesture/
