### ISSUE TITLE
Support double-tap ?

### ISSUE THREAD

**Issue by OhSoGood** [utubo/firefox-simple_gesture#69]
Hi
Do you think your addon could support double-tap (for me, to scroll down one page)? 

I know double-tap on a word by default select a word and open the context menu. I would like to be able to double-tap anywhere else (or maybe even on a text) and to make that scroll down, in an alternative to swipe down one page.

**Comment by utubo** [comment]
Firefox for android may not prevent the default behavior.
I will look into this more.


test code
```javascript

/** @name Enable double tap to page down */
document.addEventListener('dblclick', function(e) {
  e.preventDefault();
  e.stopImmediatePropagation();
 e.stopPropagation();
  scrollByPages(1, {behavior:'smooth'});
  return false;
}, {passive:false, capture:true});

```

**Comment by utubo** [comment]
Version 3.2 now supports double-tap !
thank you.
