### ISSUE TITLE
[request] Open other extension popup

### ISSUE THREAD

**Issue by AeliusSaionji** [utubo/firefox-simple_gesture#71]
Would it be possible to create a gesture that opens ublock origin's popup?
Or perhaps, call uBlock t tell it to perform an action.

Thanks

**Comment by utubo** [comment]
Sorry, this is not possible because ublock cannot accept requests from other add-ons.😢

**Comment by utubo** [comment]
📝See also
https://github.com/uBlockOrigin/uBlock-issues/issues/690

**Comment by AeliusSaionji** [comment]
Here's an idea: could we use JS to create one or multiple distinct visuals to trigger an automation?

https://github.com/Nain57/Smart-AutoClicker

Then we could use gestures to trigger an automation to do anything with any extension.

**Comment by utubo** [comment]
🤔
Like this?
(Smart AutoClicker doesn't work on my phone...)

1. Add a custom gesture.
  ```javascript
  /** @name ⛔uBlock */
  ```
2. Check `Display Command`
3. Capture ⛔ emoji with Smart AutoClicker.

**Comment by AeliusSaionji** [comment]
Yes that works! I probably will implement this in tasker instead, since autoclicker has a permanent overlay.
