### ISSUE TITLE
Cannot add extension to my collection on mozilla.org?

### ISSUE THREAD

**Issue by OhSoGood** [utubo/firefox-simple_gesture#73]
Hi
In order to add the extension to Firefox on Android, I usually add the extension first to a personal collection on mozilla.org. Yet, I cannot yours as it cannot be found :
![screenshot mozilla](https://github.com/utubo/firefox-simple_gesture/assets/1809098/381e6d41-db71-4a17-bdf5-749fd4dbf243)
Any idea how to proceed? Maybe you have to declare your extension with a special tag or setting on mozilla.org?

**Comment by utubo** [comment]
You can install it without adding it to your collection to Firefox 119.

**Comment by utubo** [comment]
Select `Any` for Badging

![Screenshot_20231017-114901~2](https://github.com/utubo/firefox-simple_gesture/assets/6848636/0dfc86a9-0c7c-4fb9-82ca-08cf2e1c6ca0)
