### ISSUE TITLE
Is it possible to undo closed tabs?

### ISSUE THREAD

**Issue by xiaoyuhaoge** [utubo/firefox-simple_gesture#74]
I don't seem to find it in the settings

**Comment by utubo** [comment]
That is not possible because the API is not supported. 😔

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions

**Comment by utubo** [comment]
Thank you for Data !
I'll get right on it.

**Comment by utubo** [comment]
version 3.3
I added `Reopen Closed Tab` in `Tab` Gestures.
You can turn on `Enable experimental features` to show it.

**Comment by utubo** [comment]
I installed Orion in iPad Air.
But, `Reopen CLosed Tab` does not work on Orion.
This works on Firefox for Android. (Windows)
🤔

**Comment by utubo** [comment]
OK.
I'll leave the source code as is.

**Comment by Dynamith** [comment]
I have studied an alternative that can be used on the mobile side, and hope to be Merged into the code.
It implements the function by listening to the creation, update and deletion of the tab page. 
The following is the code.

```javascript
// background.js
    const exec = {
        // ......

        reopen: async () => {
            // const session = (await browser.sessions.getRecentlyClosed({ maxResults: 1 }))[0];
            // if (session) {
            // 	browser.sessions.restore(session.tab ? session.tab.sessionId : session.window.sessionId);
            // }
            const url = simpleGesture_closedTabs.pop();
            if (url) browser.tabs.create({ active: true, url });
            else browser.tabs.executeScript({ code: `SimpleGesture.showTextToast('No recently closed tabs')` });
        },
        // ......
    };

    var simpleGesture_allTabs = new Map(
        (await browser.tabs.query({})).map((tabInfo) => [tabInfo.id, tabInfo.url])
    ), simpleGesture_closedTabs = [];
    browser.tabs.onCreated.addListener(tabInfo => simpleGesture_allTabs.set(tabInfo.id, tabInfo.url));
    browser.tabs.onUpdated.addListener((tabId, chgInfo) => { if (chgInfo.url) simpleGesture_allTabs.set(tabId, chgInfo.url) });
    browser.tabs.onRemoved.addListener(tabId => {
        let url = simpleGesture_allTabs.get(tabId);
        simpleGesture_allTabs.delete(tabId);
        if (!url.startsWith('about:')) {
            let index = simpleGesture_closedTabs.indexOf(url);
            if (index == -1) simpleGesture_closedTabs.push(url);
            else if (index < simpleGesture_closedTabs.length - 1) {
                simpleGesture_closedTabs.splice(index, 1);
                simpleGesture_closedTabs.push(url);
            }
        }
    });
```

**Comment by utubo** [comment]
This is a good code!
I will merge this with some fixes this month.
- The background script is unloaded after a few seconds of inactivity, so I will fix it to set closedTabs to rower.storage.session.
- Variable names e.g. `simpleGesture_allTabs` -> `allTabs` (original names are not bad...)
- Localize toast messages
- Set upper limit to `closedTabs` (fixed value 100)

Thanks for the code.

**Comment by Dynamith** [comment]
So your idea is to make the storage persistent for `closedTabs`, which is nice enough to get the behavior as close to `browser.sessions` as possible.
I am looking forward to the next version.

**Comment by utubo** [comment]
I released v.3.14. 🎉
https://github.com/utubo/firefox-simple_gesture/commit/be31ec95d02abc8a330df78edb742066ecf94107
