### ISSUE TITLE
double tap(open link in background) issue

### ISSUE THREAD

**Issue by LET33T37** [utubo/firefox-simple_gesture#80]
Double tap (open link in background) on a linked icon will trigger zoom in/out (set apz.allow_double_tap_zooming false?)

 Hard to know the new tab opened or not(only tab counts changed or by a random window "flicker effect"), 
no toast no the default "new tab opened" notification.

**Comment by utubo** [comment]
Thank you for the sample HTML.
Add-ons may not prevent zoom.😢

You can add this tag to your local home page to prevent zoom.
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by utubo** [comment]
> Hard to know the new tab opened or not

I fixed to show toast.
I will test it for a while and release it over the weekend.
