### ISSUE TITLE
Option for disable click on toast or hide toast timer

### ISSUE THREAD

**Issue by LET33T37** [utubo/firefox-simple_gesture#82]
so we can use double tap to open multiple links(close to or in the toast showing area) in background  more quickly, no need to waitting the toast disappear.

**Comment by utubo** [comment]
ok.
I'm busy right now but I think I can do it by the end of this month.

**Comment by utubo** [comment]
I released it.

If you want disable toast in some url, try this custom gesture.


`

if (location.href === 'https://utb.sakura.ne.jp/tekitou/bbb.html') {
  for (let target = SimpleGesture.target; !!target; target = target.parentNode) {
    if (target.href) {
      SimpleGesture.open(target.href, { active: false });
      break;
    }
  }
} else {
  SimpleGesture.doCommand('openLinkInBackground');
}

`

**Comment by utubo** [comment]
You can scroll, hide the toast or change the position of the toast so that you do not click on the toast.

I do not want to complicate the options.

The requirement to click on a link covered with toast seems too specific.

> reddit/inoreader/forums
Please write the url exactly.
Is that page not scrollable?
(If I try that page maybe I will change my mind.

**Comment by utubo** [comment]
Thanks for sharing the details with me👍
How about something like this? 
![PSX_20240122_150012](https://github.com/utubo/firefox-simple_gesture/assets/6848636/46171c75-22c3-4730-b863-4d1369e6f8bd)


If you use FF nightly, you can try
https://github.com/utubo/firefox-simple_gesture/releases/download/v3.11/simple-gesture.xpi
and set toast position "top"

**Comment by utubo** [comment]
v3.11 is released

**Comment by utubo** [comment]
Thank you for your time due to my persistence.🙏

Glad you like it.
