### ISSUE TITLE
THANK YOU + Feature Request

### ISSUE THREAD

**Issue by BuddhaDiedLaughing** [utubo/firefox-simple_gesture#83]
THANK YOU FOR THIS!

Can you code the app to know the difference between swiping from the outer edge of the screen vs a bit further in from any edge?

My use case is I'd be swiping left and right for going back and forth in my browsing history.

I'd use the left/right from edge of screen to be able to "page through" my tabs.  IDK how useful this would be for everybody but it sure seems smart to me.

Perhaps this is something I can configure.  It's hard to tell as the configuration menu is a bit glitchy.  It jumps me around randomly while I'm scrolling.  Quite possible Firefox issues with rendering such extensive settings.  Not a consequence of existing gestures, I'm sure.  I can live with it but could explain if I missed something obvious.

**Comment by utubo** [comment]
> Can you code the app to know the difference between swiping from the outer edge of the screen vs a bit further in from any edge?

This was supported, but some update may prevent it from showing up on the toast.
I will look into it and fix it.

>  It jumps me around randomly while I'm scrolling. 

I will try to split the page.

**Comment by utubo** [comment]
I tried to split the page.
This is still under revision.
You can try it here on FF nightly.

https://utb.sakura.ne.jp/work/simple_gesture_v3.12.dev.xpi

**Comment by BuddhaDiedLaughing** [comment]
Thank you very much.  I'll revisit, myself, after I've put out some fires.  
I think Firefox was having rendering issues.  There's a chance it's in 
there I just couldn't get the page to stay still.

You really nailed the concept and the execution.  I barely darred to hope 
of finding anything like it I'm surprised I even looked.  Seems like 
there's less and less clever lil compact, open source projects like this.  
I checked out your repos.  You seem switched on.

**Comment by utubo** [comment]
I see.
I put this issue on hold temporarily.
If you cannot resolve this, please come back.

**Comment by BuddhaDiedLaughing** [comment]
Okay, well this was my ticket.  I don't seem to be having the issue anymore. 

Still, it would be a huge improvement if users could define the gesture input area of the screen.  An edge specific preference for simply swiping from the left or right edge of the screen would help reduce the risk of the app misinterpreting interaction with Firefox as a registered gesture.  Thanks

**Comment by utubo** [comment]
>  I don't seem to be having the issue anymore.
🎉
I close this issue.

> An edge specific preference for simply swiping from the left or right edge of the screen
Simple Gesture supports this.
Actually, the squares in the input area is just for guiding.
(This is confusing and I would like to fix it.)
