### ISSUE TITLE
Haptic feedback for registered gestures (Feature Enhancement Request)

### ISSUE THREAD

**Issue by BuddhaDiedLaughing** [utubo/firefox-simple_gesture#84]
Haptic feedback for registered gestures as it's not always clear if Firefox is working on it and the toasts aren't as notification as a little vibration.

Thanks for this -either way!

**Comment by utubo** [comment]
> a little vibration.

This is a great idea.
I'm going to try it one of these days.

**Comment by utubo** [comment]
Vibration API is not supported.😢😢😢

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate

This demo does not work.
https://googlechrome.github.io/samples/vibration/
