### ISSUE TITLE
Extend add-in to allow "Open link in background" into discarded state

### ISSUE THREAD

**Issue by Glaser-Martin** [utubo/firefox-simple_gesture#86]
Can you please provide an additional Gesture or extend the existing "Open link in background" Gesture with an option to have the tab created and made visible in the tab bar without any content loaded into memory. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#muted

...says browser.tabs.create has already option discarded for that.

I tried with a Custom Gesture, but I fail, because browser.tabs is not available and I can not put additional options into open or doCommand for the browser.tabs.create.
BTW. the for loop in your second example in https://github.com/utubo/firefox-simple_gesture/wiki/Custom-gesture-examples did not work out for me, target is not going to parent nodes, I used then while like in other examples and that works.

**Comment by utubo** [comment]
This is a good idea.
I'll get right on it.

> I tried with a Custom Gesture, but I fail, because browser.tabs is not available and I can not put additional options into open or doCommand for the browser.tabs.create.

I am trying to figure out how to implement that.

> BTW. the for loop in your second example in https://github.com/utubo/firefox-simple_gesture/wiki/Custom-gesture-examples did not work out for me, target is not going to parent nodes, I used then while like in other examples and that works.

Thx ! I fixed it.

**Comment by utubo** [comment]
`discarded` does not work Firefox for Android. 😞
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#browser_compatibility

**Comment by utubo** [comment]
Might be able to do it this way.🤔
Create a `foo.html`.
```html
<script>
setTimeout(() => {
 location.href = locatio.search.substring(1);
}, 500);
</script>
```
Open `foo.html?http://...` in background.

**Comment by utubo** [comment]
v3.16 is released ! 🎉

**Comment by Glaser-Martin** [comment]
Works as desired.
Thank you so much!
