### ISSUE TITLE
If the tab I try to close with Gesture "Close Tab" is the only tab, the close kind of fails

### ISSUE THREAD

**Issue by Glaser-Martin** [utubo/firefox-simple_gesture#87]
If the tab I try to close with Gesture "Close Tab" is the only remaining tab, the tab is closed but the content remains on the screen. I can get to the desired result by opening a new tab afterwards (using the menu, Gesture is not working).

**Comment by utubo** [comment]
Same issue #64

The title of #64 is inappropriate, so I've changed it to the title of this Issue.
