### ISSUE TITLE
Request for Chrome-Compatible Version of Simple Gesture Extension

### ISSUE THREAD

**Issue by UNTRIVAL** [utubo/firefox-simple_gesture#89]
Thank you for creating this great extension! I’ve been using Simple Gesture on Firefox and find it incredibly helpful. However, I primarily work with Chrome and would love to have a version of this extension compatible with Chromium-based browsers that support extensions, such as Kiwi on Android.

I attempted to convert the current Firefox version, but encountered issues related to manifest compatibility and API support in Chrome. Could you consider providing an official Chrome version?

**Comment by utubo** [comment]
Lots of obstacles in transitioning from Manifest V2 to Manifest V3
(mainly eval the user script)
It may take some time, but I will consider it.

Thanks.

**Comment by utubo** [comment]
https://github.com/utubo/firefox-simple_gesture/releases/latest
`simple-gesture-v3.zip` does not work. 🤔

**Comment by utubo** [comment]
Done!
Read README.md.

**Comment by UNTRIVAL** [comment]
> Done! Read README.md.

It works! Would you consider uploading it to the Chrome Web Store?

**Comment by utubo** [comment]
> It works!

👍️

> Would you consider uploading it to the Chrome Web Store?

I will try.
But I am sure it won't pass review.

And.
I'm a little troubled by the fact that there is an extension in the Chrome Web store with a similar name, SimpleGestures.
