### ISSUE TITLE
Optimize the display effect of gesture trajectories

### ISSUE THREAD

**Issue by Wei-Winter** [utubo/firefox-simple_gesture#90]
Currently, Simple Gesture only has two ways to display gesture trails. I think it can refer to the effect of the smartUp Gestures extension installed in the Kiwi browser. After installing smartUp Gestures in Kiwi, you can enter its settings to enable touch gestures, and this extension also supports touch gestures. Its gesture trail can be set to show the direction of the next gesture, which I find very useful, as it's easy to forget some gestures when there are too many🥲. 

Additionally, although smartUp Gestures has been acquired and is no longer maintained, it still offers many customizable gesture features, making it excellent. Simple Gesture could consider borrowing some of its functionalities (just a small suggestion; you don't need to respond to my request, and I apologize if I have disturbed you!).

**Comment by utubo** [comment]
I am very interested in it.
But it was removed from chrome store.
A video would be helpful.
Show gesture suggestions?🤔
Thanks.

**Comment by utubo** [comment]
> You can download it here to test
> https://www.crx4chrome.com/crx/370113/

Thx!

This feature has been added.
Try 3.18!

https://github.com/utubo/firefox-simple_gesture/releases/tag/v3.18

(I will update to the Firefox store at a later date.)
